### ISSUE TITLE
Missing file 'heart_failure_clinical_records_dataset.xlsx'

### ISSUE THREAD

**Issue by HenrikBengtsson** [egenn/pdsr#6]
One more I guess; <https://class.lambdamd.org/pdsr/CrashCourse.html> uses a file `heart_failure_clinical_records_dataset.xlsx` in one of the code blocks.

**Comment by egenn** [comment]
thanks - edited to not read local xlsx file (454f8af)

**Comment by egenn** [comment]
Thanks - edited to not read local xlsx file (454f8af)
