### ISSUE TITLE
Suggestion: use 'freeze' for quarto

### ISSUE THREAD

**Issue by HenrikBengtsson** [egenn/pdsr#8]
By adding:

```diff
diff --git a/src/_quarto.yml b/src/_quarto.yml
index 85e4b938..27c892cf 100644
--- a/src/_quarto.yml
+++ b/src/_quarto.yml
@@ -91,3 +91,7 @@ format:
     css: bootstrap.lambdamd.css
     highlight-style: atom-one
     code-link: true
+
+execute:
+  freeze: auto  # re-render only when source changes
```

code blocks will be cached in the `src/_freeze/` folder.  That makes `quarto render` on the whole project run much faster.  `quarto render <file.qmd>` will still re-render the code block.  You can read about freezing at <https://quarto.org/docs/projects/code-execution.html#freeze>.

I'm using this locally, but if you're up for it, it would be neat to have in the repo.

**Comment by egenn** [comment]
I always use `quarto preview src` instead of `quarto render src`, which seems to do the same, i.e. only re-renders changed files. But I added the execute freeze as well (23ee2ff)
