### ISSUE TITLE
row.names = c(NA, -4L) ?!?

### ISSUE THREAD

**Issue by HenrikBengtsson** [egenn/pdsr#9]
At the beginning of <https://class.lambdamd.org/pdsr/dfReshape.html#wide-to-long>, there's:

```r
dat_wide <- structure(list(
    Account_ID = c(8001, 8002, 8003, 8004), 
    ...
    class = "data.frame", row.names = c(NA, -4L))
```

What's up with that `row.names = c(NA, -4L)`?  Looks like a typo/mistake by me.

**Comment by egenn** [comment]
This is just the output of `dput()` on a data.frame. 
(`structure()` needs `row.names` defined for data.frame to be created - Here could have also used `1:4`)
I edited this section to use `data.frame()` instead.

**Comment by HenrikBengtsson** [comment]
> This is just the output of `dput()` on a data.frame.

Interesting.  I've never seen that `row.names` syntax; maybe it means "use four rows but set `rownames` to `NULL`.  Oh well ...
